apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: dev
spec:
  releaseName: podinfo
  chart:
    git: git@github.com:nataz77/moodle-k8s.git
    path: charts/podinfo
    ref: master